---
title: "Introduction to Image Analysis"
author: "Rimantas Liulys"

editor:
    render-on-save: true

format:
    pdf:
        include-in-header: styles.tex

        pdf-engine: xelatex
        
        toc: true
        number-sections: true
        number-depth: 5

        fontsize: 11pt
        linestretch: 1.08

        geometry:
            - top=25mm
            - bottom=25mm
            - left=28mm
            - right=28mm

        colorlinks: true

        fig-cap-location: bottom
        tbl-cap-location: top

        code-line-numbers: true
        syntax-highlighting: github

        mainfont: "Libertinus Serif"
        sansfont: "Libertinus Sans"
        monofont: "JetBrains Mono"
---

# Assignment Description

# Code Limitations

## C++

# Assignment Details

## Image Loading

### Image Investigations

### Image loading using `libtiff`

#### Loading *tiled* and *striped* formats

##### Anomalies encountered

##### Anomaly description and reasoning

#### Loading and visualizing sub-images of the `.svs` file

#### Loading subregions of images

### Image combination

## Intensity Transormations

### Power law for intensities (disregarding constant c)

### Piece-wise linear intensity transformations

### Histogram calculation for grayscale images

### Histogram equalization

### Lookup table intensity transformations

## Spatial Filtering and Multistep Image Processing

### Image classes for pixel intensities

#### Methods of conversion

### Image blurring by spatial filtering

### Numerical approximations of derivative operators

### Image sharpening using an intermediate Laplacian calculation

#### Benefits

#### Drawbacks

### Multistep image processing

## Image Transformations

### Calculation of index-to-local and local-to-world transformations

### Composite affine transformations

### Nearest Neighbor and Bi-linear Interpolation for visualization of transformed images

### Visualization of affine transformations

#### Nearest Neighbor type

#### Bi-linear type

### QA of AI classification of kidney histology images